# Bootable Container: Apache HTTPD Web Server
# Base image: CentOS Stream 9 bootc
#
# BUILD:
#   export USERNAME=<your-quay-username>
#   podman build -t quay.io/${USERNAME}/bootc-webserver:v1.0 .

FROM quay.io/centos-bootc/centos-bootc:stream9

# Theme customization build args (defaults to v1.0 red theme)
ARG THEME_COLOR="#ee0000"
ARG THEME_COLOR_DARK="#a30000"
ARG THEME_COLOR_LIGHT="#ff4d4d"
ARG VERSION="1.0"
ARG SUBTITLE="The Operating System as a Container Image"

# Update system and install required packages
# cloud-init is required for VM cloud-init configuration to work
RUN dnf -y update && \
    dnf -y install tmux httpd vim-minimal cloud-init && \
    dnf clean all && \
    rm -rf /var/cache/dnf

# Enable cloud-init services
RUN systemctl enable cloud-init cloud-init-local cloud-config cloud-final

# Create a user with password (password: redhat)
RUN useradd -m -G wheel bootc-user && \
    echo 'bootc-user:redhat' | chpasswd

# Configure passwordless sudo for wheel group
RUN echo "%wheel        ALL=(ALL)       NOPASSWD: ALL" > /etc/sudoers.d/wheel-sudo

# Configure Apache
# Move /var/www to /usr/share/www for immutability
RUN systemctl enable httpd && \
    mv /var/www /usr/share/www && \
    sed -i 's,/var/www,/usr/share/www,' /etc/httpd/conf/httpd.conf

# Add custom content
COPY index.html /usr/share/www/html/index.html

# Apply theme customization
RUN sed -i \
    -e "s|THEME_COLOR_DARK|${THEME_COLOR_DARK}|g" \
    -e "s|THEME_COLOR_LIGHT|${THEME_COLOR_LIGHT}|g" \
    -e "s|THEME_COLOR|${THEME_COLOR}|g" \
    -e "s|APP_VERSION|${VERSION}|g" \
    -e "s|APP_SUBTITLE|${SUBTITLE}|g" \
    /usr/share/www/html/index.html

# Expose HTTP port
EXPOSE 80

# Labels for image identification
ARG VERSION
LABEL name="bootc-webserver" \
      version="${VERSION}" \
      description="CentOS Stream 9 bootc-based Apache web server"
